[package]
name = "frontend-tauri"
version = "0.0.1"
publish = false
edition = "2024"

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.9", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
