[workspace]
members = ["crates/backend", "crates/frontend", "crates/util"]
resolver = "2"

[workspace.dependencies]
util = { path = "crates/util" }

candid = { version = "0.10", default-features = false }
serde = { version = "1.0", features = ["derive"] }
